const lessonData = {};

lessonData["01_Affen.mp3"] = [{
    text: "1. Aggressive Affen. Wissenschaftler wollten herausfinden, wie eine Gruppe gewalttätige Regeln lernt. Sie setzten fünf Schimpansen in einen Käfig. Sie hängten leckere gelbe Bananen hoch oben an die Decke. Wenn ein Affe hochkletterte, um die Bananen zu holen, sprühten die Wissenschaftler alle fünf Affen mit sehr kaltem, unangenehmem Wasser nass. Nach ein paar Malen lernten die Affen eine neue Regel: Die Bananen verursachen das schlechte Wasser. Um das kalte Wasser zu stoppen, griff die Gruppe jeden Affen an, der versuchte, ans Futter zu kommen. Dann wechselten die Wissenschaftler die Affen aus. Sie nahmen einen alten Affen heraus und setzten einen neuen hinein. Der Neue kannte das kalte Wasser nicht. Er versuchte sofort, die Bananen zu greifen. Die anderen vier Affen griffen ihn sofort an und verprügelten ihn. Die Wissenschaftler ersetzten langsam alle ursprünglichen Affen. Am Ende waren fünf komplett neue Affen im Käfig. Das kalte Wasser wurde nie wieder benutzt. Doch immer, wenn ein Affe nach den Bananen griff, griff die Gruppe ihn wütend an. Die Affen setzten dieses gewalttätige Verhalten fort. Sie prügelten sich einfach, weil es die etablierte Regel ihrer Gesellschaft war. Sie folgten der Gruppenregel blind, ohne zu wissen, warum sie existierte.",
    dict: { "wissenschaftler":"bilim insanları", "herausfinden":"öğrenmek/keşfetmek", "gewalttätige":"şiddetli", "regeln":"kurallar", "schimpansen":"şempanzeler", "käfig":"kafes", "hängten":"astılar", "leckere":"lezzetli", "bananen":"muzlar", "decke":"tavan", "hochkletterte":"yukarı tırmandı", "holen":"almak", "sprühten":"püskürttüler", "kaltem":"soğuk", "unangenehmem":"rahatsız edici", "wasser":"su", "nass":"ıslak", "verursachen":"sebep olmak", "stoppen":"durdurmak", "griff":"saldırdı", "futter":"yiyecek", "wechselten":"değiştirdiler", "aus":"dışarı", "alten":"eski", "neuen":"yeni", "kannte":"biliyordu", "greifen":"yakalamak", "verprügelten":"dövdüler", "ersetzten":"değiştirdiler", "ursprünglichen":"orijinal", "ende":"son", "benutzt":"kullanıldı", "wütend":"kızgın", "verhalten":"davranış", "fort":"devam (fortsetzen: devam ettirmek)", "prügelten":"dövdüler", "etablierte":"yerleşik", "gesellschaft":"toplum", "folgten":"takip ettiler", "blind":"körü körüne", "existierte":"var oldu" },
    questions: [ {q:"Setzten die Wissenschaftler Schimpansen in einen Käfig?", a_de:"Ja", a_tr:"Evet"}, {q:"Hingen Äpfel an der Decke?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurden die Affen mit heißem Wasser besprüht?", a_de:"Nein", a_tr:"Hayır"}, {q:"Griffen die Affen den neuen Affen an?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurden am Ende alle alten Affen ersetzt?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde das kalte Wasser später wieder benutzt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Folgten die neuen Affen der Regel blind?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["02_Ameisen.mp3"] = [{
    text: "2. Ameisen-Opfer. Ameisenkolonien haben eine sehr strenge Gesellschaft, um gefährliche Zeiten zu überleben. Manchmal gibt es absolut kein Futter für die Ameisen. Die Kolonie beginnt zu hungern und zu sterben. Um die Gruppe zu retten, opfert eine einzelne Ameise mutig ihr eigenes Leben. Diese spezielle Ameise ist immer die älteste und schwächste in der Kolonie. Zwanzig junge, starke Kriegerameisen verlassen mit der alten Ameise das Nest. Sie suchen eine Tarantel, eine riesige, giftige Spinne. Wenn sie die Spinne finden, verstecken sich die jungen Krieger hinter Steinen. Die alte Ameise geht langsam direkt auf die gefährliche Spinne zu. Die hungrige Tarantel sieht die alte Ameise sofort und greift an. Sie setzt all ihr tödliches Gift ein, um die einzelne alte Ameise zu töten. Nach dem Angriff hat die Spinne kein Gift mehr im Körper. Plötzlich springen die zwanzig versteckten Kriegerameisen hervor. Sie greifen die wehrlose Spinne leicht an und töten sie. Sie tragen den riesigen Spinnenkörper vorsichtig zurück in ihre hungrige Kolonie. Dank des mutigen Opfers der ältesten Ameise bekommt die ganze Kolonie genug Futter, um die schreckliche Knappheit zu überstehen.",
    dict: { "ameisenkolonien":"karınca kolonileri", "strenge":"katı", "überleben":"hayatta kalmak", "hungern":"açlık çekmek", "sterben":"ölmek", "retten":"kurtarmak", "opfert":"feda eder", "einzelne":"tek", "mutig":"cesurca", "eigenes":"kendi", "leben":"hayat", "älteste":"en yaşlı", "schwächste":"en zayıf", "kriegerameisen":"savaşçı karıncalar", "verlassen":"terk eder", "nest":"yuva", "suchen":"ararlar", "tarantel":"tarantula", "riesige":"devasa", "giftige":"zehirli", "spinne":"örümcek", "verstecken":"saklanırlar", "steinen":"taşlar", "direkt":"doğrudan", "greift":"saldırır", "tödliches":"ölümcül", "gift":"zehir", "angriff":"saldırı", "körper":"vücut", "springen":"zıplarlar", "hervor":"öne/dışarı", "wehrlose":"savunmasız", "leicht":"kolayca", "tragen":"taşırlar", "spinnenkörper":"örümcek cesedi", "vorsichtig":"dikkatlice", "dank":"sayesinde", "opfers":"fedakarlık", "genug":"yeterli", "schreckliche":"korkunç", "knappheit":"kıtlık", "überstehen":"atlatmak" },
    questions: [ {q:"Opfert sich die jüngste Ameise für die Kolonie?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verlassen zwanzig junge Kriegerameisen das Nest?", a_de:"Ja", a_tr:"Evet"}, {q:"Suchen die Ameisen eine giftige Tarantel?", a_de:"Ja", a_tr:"Evet"}, {q:"Setzt die Tarantel all ihr Gift gegen die alte Ameise ein?", a_de:"Ja", a_tr:"Evet"}, {q:"Hat die Spinne nach dem Angriff noch viel Gift?", a_de:"Nein", a_tr:"Hayır"}, {q:"Töten die jungen Ameisen die Spinne leicht?", a_de:"Ja", a_tr:"Evet"}, {q:"Bekommt die Kolonie am Ende genug Futter?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["03_Bienen.mp3"] = [{
    text: "3. Bienen-Demokratie. Viele denken, nur Menschen haben Wahlen, aber einige Tiere nutzen auch demokratische Systeme. Honigbienen sind ein perfektes Beispiel für tierische Demokratie. Obwohl die Anführerin des Stocks Königin heißt, treffen die Bienen wichtige Entscheidungen gemeinsam. Wenn ihr alter Stock zu voll wird, brauchen sie ein neues Zuhause. Die Späherbienen erkunden verschiedene Plätze. Dann kommen sie zurück und stimmen über den besten Ort ab – durch einen speziellen Tanz in der Luft. Nach dem Bau des neuen Stocks müssen sie eine brandneue Königin wählen. Meist gibt es drei oder vier junge Kandidatinnen. Die Bienen halten eine echte, demokratische Wahl ab. Die Kandidatinnen versuchen, Anhänger zu gewinnen. Die junge Biene mit den meisten Unterstützern wird offiziell die neue Königin. Die anderen Bienen kämpfen nicht oder starten keinen Krieg wegen des Ergebnisses. Sie akzeptieren die neue Königin komplett ohne Streit. Sie respektieren die Mehrheitsentscheidung der Kolonie. Dieses friedliche System hält die Bienen organisiert und stark. Sie zeigen uns, dass Wählen und das Endergebnis zu akzeptieren eine sehr kluge, natürliche Methode ist, um eine große Gesellschaft erfolgreich zu führen.",
    dict: { "wahlen":"seçimler", "demokratische":"demokratik", "systeme":"sistemler", "honigbienen":"bal arıları", "perfektes":"mükemmel", "beispiel":"örnek", "tierische":"hayvansal", "obwohl":"rağmen", "anführerin":"kadın lider", "königin":"kraliçe", "heißt":"adlandırılır", "entscheidungen":"kararlar", "gemeinsam":"birlikte", "voll":"dolu", "brauchen":"ihtiyaç duyarlar", "zuhause":"ev", "späherbienen":"kâşif arılar", "erkunden":"keşfederler", "verschiedene":"farklı", "plätze":"yerler", "stimmen":"oy verirler", "tanz":"dans", "luft":"hava", "bau":"inşaat", "brandneue":"yepyeni", "wählen":"seçmek", "kandidatinnen":"kadın adaylar", "echte":"gerçek", "anhänger":"takipçiler", "gewinnen":"kazanmak", "meisten":"en çok", "unterstützern":"destekçiler", "offiziell":"resmi olarak", "kämpfen":"savaşırlar", "krieg":"savaş", "ergebnisses":"sonuç", "akzeptieren":"kabul ederler", "streit":"tartışma/kavga", "respektieren":"saygı duyarlar", "mehrheitsentscheidung":"çoğunluk kararı", "friedliche":"huzurlu", "kluge":"zeki", "natürliche":"doğal", "erfolgreich":"başarılı", "führen":"yönetmek/yönlendirmek" },
    questions: [ {q:"Treffen Honigbienen wichtige Entscheidungen gemeinsam?", a_de:"Ja", a_tr:"Evet"}, {q:"Stimmen die Späherbienen durch einen Tanz in der Luft ab?", a_de:"Ja", a_tr:"Evet"}, {q:"Gibt es meist zehn Kandidatinnen für die neue Königin?", a_de:"Nein", a_tr:"Hayır"}, {q:"Versuchen die Kandidatinnen Anhänger zu gewinnen?", a_de:"Ja", a_tr:"Evet"}, {q:"Starten die anderen Bienen einen Krieg wegen des Ergebnisses?", a_de:"Nein", a_tr:"Hayır"}, {q:"Akzeptieren sie die neue Königin ohne Streit?", a_de:"Ja", a_tr:"Evet"}, {q:"Respektieren die Bienen die Mehrheitsentscheidung?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["04_Schlangen.mp3"] = [{
    text: "4. Kugelfressende Schlangen. In der Wildnis ist es meistens sehr gut, unglaublich schnelle Reflexe zu haben. Schlangen sind ein tolles Beispiel. Die Reaktionszeit einer Schlange ist extrem schnell. Es dauert nur einen Bruchteil einer Sekunde, bis sie auf Gefahr reagiert. Das macht sie zu einem der absolut schnellsten Tiere in der Natur. Manchmal kann zu viel Schnelligkeit und Aggressivität jedoch ein furchtbarer Fehler sein. Stell dir einen Cowboy vor, der auf einem Pferd durch die Wüste reitet. Plötzlich erscheint eine gefährliche Klapperschlange auf dem Boden. Der Cowboy zieht schnell seine Waffe und schießt auf die Schlange. Man könnte denken, die Kugel sei zu schnell für die Schlange. Aber hier ist die erstaunliche Wahrheit: Der Reflex der Schlange ist tatsächlich schneller als die Kugel. Die Schlange sieht die schnelle Kugel klar auf ihren Kopf zukommen. Statt wegzuziehen, um ihr Leben zu retten, denkt die aggressive Schlange, die Kugel sei ein kleines Tier. Sie versucht schnell, die Kugel zu beißen. Wegen dieses wütenden Reflexes geht die Kugel direkt in ihr Maul und tötet sie. Wenn die Schlange einfach ausgewichen wäre, würde sie leben. Ihre eigene aggressive Reaktion verursacht ihren tragischen Tod.",
    dict: { "wildnis":"vahşi doğa", "schnelle":"hızlı", "reflexe":"refleksler", "schlangen":"yılanlar", "reaktionszeit":"tepki süresi", "extrem":"aşırı", "dauert":"sürer", "bruchteil":"küçük bir parça", "sekunde":"saniye", "gefahr":"tehlike", "reagiert":"tepki verir", "schnellsten":"en hızlı", "schnelligkeit":"hız", "aggressivität":"agresiflik", "furchtbarer":"korkunç", "fehler":"hata", "cowboy":"kovboy", "pferd":"at", "wüste":"çöl", "reitet":"ata biner", "erscheint":"ortaya çıkar", "klapperschlange":"çıngıraklı yılan", "boden":"zemin", "zieht":"çeker", "waffe":"silah", "schießt":"ateş eder", "kugel":"mermi", "erstaunliche":"şaşırtıcı", "wahrheit":"gerçek", "tatsächlich":"aslında", "klar":"net/açık", "kopf":"baş/kafa", "zukommen":"üzerine gelmek", "wegzuziehen":"geri çekilmek", "retten":"kurtarmak", "kleines":"küçük", "tier":"hayvan", "beißen":"ısırmak", "wütenden":"kızgın", "maul":"ağız", "tötet":"öldürür", "ausgewichen":"kaçınmış", "verursacht":"sebep olur", "tragischen":"trajik", "tod":"ölüm" },
    questions: [ {q:"Haben Schlangen sehr langsame Reflexe?", a_de:"Nein", a_tr:"Hayır"}, {q:"Reagieren Schlangen in einem Bruchteil einer Sekunde?", a_de:"Ja", a_tr:"Evet"}, {q:"Schießt der Cowboy auf die Klapperschlange?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist der Reflex der Schlange schneller als die Kugel?", a_de:"Ja", a_tr:"Evet"}, {q:"Denkt die Schlange, die Kugel sei ein kleines Tier?", a_de:"Ja", a_tr:"Evet"}, {q:"Zieht die Schlange ihren Kopf weg, um sich zu retten?", a_de:"Nein", a_tr:"Hayır"}, {q:"Geht die Kugel direkt in das Maul der Schlange?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["05_Delfine.mp3"] = [{
    text: "5. Chaotische Robben und organisierte Delfine. Robben und Delfine leben im selben Ozean und fressen genau dieselbe Art von Fisch. Doch sie haben völlig unterschiedliche Jagdstrategien. Robben leben meist in großen Gruppen zusammen, verhalten sich aber sehr egoistisch. Wenn eine Gruppe Robben viele Fische findet, springen alle gleichzeitig ins Wasser. Jede versucht aggressiv, so viel Futter wie möglich für sich selbst zu fangen. Dieses verrückte Chaos verscheucht die Fische schnell. Wegen ihres egoistischen Verhaltens fangen die Robben nur wenige Fische. Delfine hingegen sind unglaublich klug und organisiert. Wenn Delfine Fische finden, arbeiten sie als perfektes Team zusammen. Sie schwimmen in engen Kreisen um die Fische, sodass diese nicht entkommen können. Die schwächsten oder jüngsten Delfine essen zuerst. Dann wechseln sie langsam die Plätze mit den anderen. Sie essen abwechselnd und schwimmen Kreise. Sie setzen diese organisierte Teamarbeit fort, bis jeder Delfin seinen fairen Anteil bekommt. Wenn die gierigen Robben gelernt hätten, geduldig wie die klugen Delfine zusammenzuarbeiten, würden sie leicht viel mehr Futter für die ganze Gruppe fangen.",
    dict: { "robben":"foklar", "delfine":"yunuslar", "ozean":"okyanus", "fressen":"yerler", "genau":"tam olarak", "fisch":"balık", "unterschiedliche":"farklı", "jagdstrategien":"avlanma stratejileri", "gruppen":"gruplar", "verhalten":"davranırlar", "egoistisch":"bencilce", "fische":"balıklar", "springen":"zıplarlar", "gleichzeitig":"aynı anda", "fangen":"yakalamak", "verrückte":"çılgın", "chaos":"kaos", "verscheucht":"korkutup kaçırır", "wenige":"az", "hingegen":"buna karşılık", "klug":"zeki", "organisiert":"organize", "arbeiten":"çalışırlar", "perfektes":"mükemmel", "team":"takım", "schwimmen":"yüzerler", "engen":"dar", "kreisen":"daireler", "entkommen":"kaçmak", "schwächsten":"en zayıf", "jüngsten":"en genç", "essen":"yerler", "zuerst":"ilk önce", "wechseln":"değiştirirler", "plätze":"yerler", "abwechselnd":"sırayla", "fairen":"adil", "anteil":"pay", "gierigen":"açgözlü", "gelernt":"öğrenmiş", "geduldig":"sabırlı", "zusammenzuarbeiten":"birlikte çalışmak" },
    questions: [ {q:"Leben Robben und Delfine im selben Ozean?", a_de:"Ja", a_tr:"Evet"}, {q:"Verhalten sich Robben beim Jagen sehr egoistisch?", a_de:"Ja", a_tr:"Evet"}, {q:"Fangen die Robben wegen ihres Chaos sehr viele Fische?", a_de:"Nein", a_tr:"Hayır"}, {q:"Arbeiten Delfine als perfektes Team zusammen?", a_de:"Ja", a_tr:"Evet"}, {q:"Essen die stärksten Delfine immer zuerst?", a_de:"Nein", a_tr:"Hayır"}, {q:"Schwimmen die Delfine abwechselnd in Kreisen?", a_de:"Ja", a_tr:"Evet"}, {q:"Bekommt jeder Delfin seinen fairen Anteil?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["06_Oktopus.mp3"] = [{
    text: "6. Cleverer Oktopus. Wissenschaftler glauben, dass der Oktopus wahrscheinlich das intelligenteste Tier im Ozean ist. Sie machten ein spezielles Experiment, um tierische Intelligenz zu testen. Sie nahmen einen sehr klugen Hund, einen klugen Schimpansen und einen Oktopus. Sie machten alle drei Tiere sehr hungrig. Dann steckten sie leckeres Futter in eine Plastikflasche mit festem Deckel. Der Hund und der Schimpanse versuchten es hart, konnten die Flasche aber nicht öffnen. Sie gaben nach ein paar Stunden auf. Der clevere Oktopus nutzte jedoch seine starken Arme, um den Plastikdeckel aufzuschrauben. Er öffnete die Flasche in einer halben Stunde und fraß das Futter. Beim nächsten Mal öffnete der Oktopus den Deckel in nur zwanzig Sekunden. Aber das Erstaunlichste kam danach. Dieser smarte Oktopus brachte anderen Oktopussen bei, wie man die Flaschen öffnet. Innerhalb von drei Tagen öffneten alle anderen Oktopusse ihre Flaschen leicht in zwanzig Sekunden. Leider lebt der durchschnittliche Oktopus nur etwa drei kurze Jahre. Wenn diese unglaublich klugen Wesen viel länger leben würden, könnten sie vielleicht eine komplexe, fortschrittliche Zivilisation am Meeresboden aufbauen.",
    dict: { "wissenschaftler":"bilim insanları", "glauben":"inanırlar", "oktopus":"ahtapot", "wahrscheinlich":"muhtemelen", "intelligenteste":"en zeki", "experiment":"deney", "testen":"test etmek", "hund":"köpek", "schimpansen":"şempanze", "hungrig":"aç", "steckten":"koydular", "plastikflasche":"plastik şişe", "festem":"sıkı/sert", "deckel":"kapak", "konnten":"bildiler", "öffnen":"açmak", "gaben":"pes ettiler (aufgeben)", "stunden":"saatler", "nutzte":"kullandı", "starken":"güçlü", "arme":"kollar", "plastikdeckel":"plastik kapak", "aufzuschrauben":"çevirerek açmak", "halben":"yarım", "fraß":"yedi", "nächsten":"sonraki", "zwanzig":"yirmi", "sekunden":"saniyeler", "erstaunlichste":"en şaşırtıcı", "smarte":"akıllı", "brachte":"öğretti (beibringen)", "innerhalb":"içinde", "tagen":"günler", "leider":"ne yazık ki", "durchschnittliche":"ortalama", "kurze":"kısa", "wesen":"varlıklar", "komplexe":"karmaşık", "fortschrittliche":"ileri/gelişmiş", "zivilisation":"medeniyet", "meeresboden":"deniz tabanı", "aufbauen":"inşa etmek" },
    questions: [ {q:"Machten die Wissenschaftler ein Experiment zur Intelligenz?", a_de:"Ja", a_tr:"Evet"}, {q:"Konnte der Hund die Flasche öffnen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Schraubte der Oktopus den Deckel auf?", a_de:"Ja", a_tr:"Evet"}, {q:"Öffnete er die Flasche beim zweiten Mal in zwanzig Sekunden?", a_de:"Ja", a_tr:"Evet"}, {q:"Brachte er anderen Oktopussen bei, wie man das macht?", a_de:"Ja", a_tr:"Evet"}, {q:"Lernten die anderen Oktopusse das in drei Tagen?", a_de:"Ja", a_tr:"Evet"}, {q:"Lebt der durchschnittliche Oktopus 50 Jahre lang?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["07_Krabben.mp3"] = [{
    text: "7. Krebs-Mentalität. Genau wie manche Menschen zeigen Krabben oft ein sehr negatives und neidisches Verhalten. Wenn eine einzelne Krabbe allein in einem Korb ist, kann sie leicht die Seiten hochklettern. Sie erreicht schnell die Oberkante und entkommt in die Freiheit. Doch die Situation ändert sich komplett, wenn zwei oder mehr Krabben im selben Korb sind. Wenn eine mutige Krabbe versucht, nach oben zu klettern, werden die anderen aggressiv. Sie greifen hoch und ziehen die kletternde Krabbe zurück nach unten. Statt einander aus der Falle zu helfen, sabotieren sie sich ständig gegenseitig. Ihre innere Eifersucht sorgt dafür, dass niemand je aus dem Korb entkommt. Dieses seltsame Verhalten ist unglaublich zuverlässig. Fischer auf der ganzen Welt kennen diese natürliche Gewohnheit. Sie legen nie einen Deckel auf ihre Krebskörbe, weil sie wissen, dass die Krabben einander fröhlich für immer gefangen halten. Dieses extrem selbstzerstörerische Muster schuf den berühmten menschlichen Begriff „Krebs-Mentalität“. Er beschreibt neidische Menschen, die jeden herunterziehen, der erfolgreich wird – einfach aus Neid auf ihren Fortschritt.",
    dict: { "manche":"bazı", "zeigen":"gösterirler", "krabben":"yengeçler", "negatives":"negatif", "neidisches":"kıskanç", "einzelne":"tek", "korb":"sepet", "hochklettern":"yukarı tırmanmak", "erreicht":"ulaşır", "oberkante":"üst kenar", "entkommt":"kaçar", "freiheit":"özgürlük", "situation":"durum", "ändert":"değişir", "mutige":"cesur", "aggressiv":"agresif", "greifen":"yakalarlar", "ziehen":"çekerler", "kletternde":"tırmanan", "unten":"aşağı", "statt":"yerine", "einander":"birbirlerine", "falle":"tuzak", "helfen":"yardım etmek", "sabotieren":"sabote ederler", "ständig":"sürekli", "gegenseitig":"karşılıklı", "innere":"içsel", "eifersucht":"kıskançlık", "sorgt":"sağlar", "niemand":"hiç kimse", "seltsame":"tuhaf", "zuverlässig":"güvenilir", "fischer":"balıkçılar", "natürliche":"doğal", "gewohnheit":"alışkanlık", "gefangen":"tutsak", "halten":"tutarlar", "selbstzerstörerische":"kendi kendini yok eden", "muster":"kalıp/model", "schuf":"yarattı", "menschlichen":"insani", "begriff":"terim", "beschreibt":"tanımlar", "neid":"kıskançlık", "fortschritt":"ilerleme" },
    questions: [ {q:"Kann eine einzelne Krabbe leicht aus dem Korb klettern?", a_de:"Ja", a_tr:"Evet"}, {q:"Helfen sich zwei Krabben gegenseitig aus dem Korb?", a_de:"Nein", a_tr:"Hayır"}, {q:"Ziehen die anderen Krabben die kletternde Krabbe nach unten?", a_de:"Ja", a_tr:"Evet"}, {q:"Sabotieren sie sich ständig gegenseitig?", a_de:"Ja", a_tr:"Evet"}, {q:"Legen Fischer immer einen Deckel auf ihre Krebskörbe?", a_de:"Nein", a_tr:"Hayır"}, {q:"Beschreibt der Begriff neidische Menschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Ziehen diese Menschen andere erfolgreichere Menschen nach unten?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["08_Hunde.mp3"] = [{
    text: "8. Hunde in der U-Bahn. Moskau ist eine sehr große Stadt mit einem berühmten U-Bahn-System. Es leben auch etwa 35.000 streunende Hunde in der Stadt. Diese Hunde haben kein Zuhause oder Besitzer. Die meisten leben weit weg vom belebten Stadtzentrum, in den ruhigen Vororten. Doch in den Vororten gibt es nicht genug Futter für all diese hungrigen Hunde. Deshalb haben die klugen Hunde gelernt, die öffentlichen U-Bahn-Züge zu nutzen. Sie verstehen die verschiedenen Linien und den täglichen Fahrplan genau. Jeden Morgen betreten sie die Stationen und fahren mit den menschlichen Pendlern ins Stadtzentrum. Den Tag verbringen sie damit, Futter in den belebten Straßen zu finden. Abends nehmen sie den richtigen Zug zurück in ihre ruhigen Vorort-Heime. Die Menschen in Moskau sind meist sehr nett zu diesen klugen Hunden. Die Hunde haben ausgezeichnete öffentliche Manieren gelernt. Sie legen sich höflich auf den Boden zwischen den Passagiersitzen. Sie bellen nie laut oder belästigen jemanden im Zug. Weil sie so ruhig und höflich sind, beschweren sich die Menschen nie darüber, ihre Morgenfahrt mit diesen erstaunlichen tierischen Passagieren zu teilen.",
    dict: { "moskau":"moskova", "stadt":"şehir", "u-bahn-system":"metro sistemi", "streunende":"sokak/başıboş", "hunde":"köpekler", "besitzer":"sahip", "stadtzentrum":"şehir merkezi", "ruhigen":"sakin", "vororten":"banliyöler", "hungrigen":"aç", "öffentlichen":"kamusal", "nutzen":"kullanmak", "verstehen":"anlarlar", "linien":"hatlar", "täglichen":"günlük", "fahrplan":"hareket saati", "morgen":"sabah", "betreten":"girerler", "stationen":"istasyonlar", "fahren":"giderler", "menschlichen":"insani", "pendlern":"işe gidip gelenler", "verbringen":"geçirirler", "straßen":"caddeler", "abends":"akşamları", "richtigen":"doğru", "heime":"evler", "nett":"kibar", "ausgezeichnete":"mükemmel", "manieren":"davranışlar", "höflich":"kibarca", "boden":"zemin", "passagiersitzen":"yolcu koltukları", "bellen":"havlarlar", "laut":"yüksek sesle", "belästigen":"rahatsız ederler", "beschweren":"şikayet ederler", "morgenfahrt":"sabah yolculuğu", "erstaunlichen":"şaşırtıcı", "teilen":"paylaşmak" },
    questions: [ {q:"Gibt es in Moskau etwa 35.000 streunende Hunde?", a_de:"Ja", a_tr:"Evet"}, {q:"Fahren die Hunde mit der U-Bahn ins Stadtzentrum?", a_de:"Ja", a_tr:"Evet"}, {q:"Verstehen die Hunde den täglichen Fahrplan?", a_de:"Ja", a_tr:"Evet"}, {q:"Finden sie im Stadtzentrum ihr Futter?", a_de:"Ja", a_tr:"Evet"}, {q:"Bellen die Hunde laut im Zug?", a_de:"Nein", a_tr:"Hayır"}, {q:"Legen sie sich höflich auf den Boden?", a_de:"Ja", a_tr:"Evet"}, {q:"Beschweren sich die Menschen oft über die Hunde?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["09_Empathie.mp3"] = [{
    text: "9. Empathische Maus. Viele denken, nur Menschen können die Gefühle anderer verstehen. Doch Wissenschaftler haben kürzlich entdeckt, dass einfache Mäuse tatsächlich auch Empathie empfinden können. In einem interessanten Experiment setzten Wissenschaftler eine kleine Maus in einen engen, unangenehmen Käfig. Sie machten diese Maus sehr hungrig. Dann setzten sie eine zweite, freie Maus in denselben Raum. Die freie Maus sah das gefangene Tier. Sie begann sofort zu helfen. Nach harter Arbeit öffnete sie schließlich die Käfigtür und befreite die hungrige Maus. Am nächsten Tag wiederholten die Wissenschaftler den Test genau gleich. Sie setzten eine brandneue hungrige Maus in den engen Käfig. Dann brachten sie die allererste Maus – die, die am Tag zuvor gefangen war – zurück in den Raum. Diese Maus rannte sofort zum Käfig. Sie arbeitete schnell, um die neue Maus zu befreien. Sie tat es ohne Zögern. Die Maus erinnerte sich klar an das schreckliche Gefühl, gefangen und hungrig zu sein. Sie empfand echte Traurigkeit für die neue Gefangene. Das beweist, dass Tiere emotionalen Schmerz teilen und aktiv versuchen können, einander beim Überleben zu helfen.",
    dict: { "gefühle":"duygular", "entdeckt":"keşfetti", "einfache":"basit", "mäuse":"fareler", "empathie":"empati", "empfinden":"hissetmek", "experiment":"deney", "enge":"dar", "unangenehmen":"rahatsız edici", "käfig":"kafes", "hungrig":"aç", "zweite":"ikinci", "freie":"özgür", "raum":"oda", "gefangene":"tutsak", "begann":"başladı", "harter":"zor/sıkı", "arbeit":"iş", "öffnete":"açtı", "käfigtür":"kafes kapısı", "befreite":"kurtardı", "wiederholten":"tekrarladılar", "genau":"tam olarak", "gleich":"aynı", "brandneue":"yepyeni", "allererste":"en ilk", "zuvor":"önce", "rannte":"koştu", "zögern":"tereddüt", "erinnerte":"hatırladı", "schreckliche":"korkunç", "traurigkeit":"üzüntü", "beweist":"kanıtlar", "emotionalen":"duygusal", "schmerz":"acı", "aktiv":"aktif", "versuchen":"denemek" },
    questions: [ {q:"Setzten die Wissenschaftler eine Maus in einen unangenehmen Käfig?", a_de:"Ja", a_tr:"Evet"}, {q:"Begann die freie Maus sofort zu helfen?", a_de:"Ja", a_tr:"Evet"}, {q:"Befreite die freie Maus die hungrige Maus?", a_de:"Ja", a_tr:"Evet"}, {q:"Setzten die Wissenschaftler am nächsten Tag wieder die gleiche gefangene Maus in den Käfig?", a_de:"Nein", a_tr:"Hayır"}, {q:"Erinnerte sich die erste Maus an das schreckliche Gefühl?", a_de:"Ja", a_tr:"Evet"}, {q:"Arbeitete sie schnell, um die neue Maus zu befreien?", a_de:"Ja", a_tr:"Evet"}, {q:"Beweist das, dass Mäuse Empathie empfinden können?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["10_Angst.mp3"] = [{
    text: "10. Ängstliche Mäuse. Menschen glauben oft, Mäuse hätten von Natur aus eine tiefe Angst vor Katzen. Doch in Wirklichkeit stimmt das nicht. Mäuse lernen diese Angst tatsächlich aus ihrer Gesellschaft, und die Angst breitet sich schnell unter ihnen aus. Angst ist eine ansteckende Emotion. Wissenschaftler machten einen Test, um das zu beweisen. Sie setzten eine große, aggressive Katze in eine Glasbox. Sie setzten eine Labormaus in eine andere Glasbox daneben. Als sie den Vorhang öffneten, versuchte die wütende Katze anzugreifen. Die Labormaus zeigte überhaupt keine Angst. Sie hatte in ihrem ganzen Leben noch nie eine Katze gesehen. Zwei Stunden später setzten die Wissenschaftler eine wilde Straßenmaus neben die Labormaus. Sie öffneten den Vorhang wieder. Die Katze versuchte aggressiv, sie zu fangen. Die wilde Straßenmaus hatte panische Angst und rannte schnell weg, um sich zu verstecken. Plötzlich begann auch die ruhige Labormaus in Panik wegzurennen. Die Labormaus lernte die Angst einfach, indem sie die Panik der anderen Maus beobachtete. Sie lernte die Regeln des Überlebens und Vorurteils direkt von ihrer Nachbarin – das beweist, dass soziale Ängste gelehrt werden, nicht angeboren sind.",
    dict: { "natur":"doğa", "angst":"korku", "katzen":"kediler", "wirklichkeit":"gerçekte", "stimmt":"doğrudur", "gesellschaft":"toplum", "breitet":"yayılır", "ansteckende":"bulaşıcı", "emotion":"duygu", "beweisen":"kanıtlamak", "aggressive":"agresif", "katze":"kedi", "glasbox":"cam kutu", "labormaus":"laboratuvar faresi", "daneben":"yanına", "vorhang":"perde", "zeigte":"gösterdi", "überhaupt":"hiç", "stunden":"saatler", "wilde":"vahşi", "straßenmaus":"sokak faresi", "panische":"panik", "weg":"uzağa", "verstecken":"saklanmak", "wegzurennen":"kaçmak", "indem":"yaparak/ederek", "beobachtete":"gözlemledi", "regeln":"kurallar", "überlebens":"hayatta kalma", "vorurteils":"önyargı", "nachbarin":"komşu", "soziale":"sosyal", "ängste":"korkular", "gelehrt":"öğretilmiş", "angeboren":"doğuştan" },
    questions: [ {q:"Ist die Angst vor Katzen bei Mäusen angeboren?", a_de:"Nein", a_tr:"Hayır"}, {q:"Setzten die Wissenschaftler eine Katze in eine Glasbox?", a_de:"Ja", a_tr:"Evet"}, {q:"Zeigte die Labormaus beim ersten Mal große Angst?", a_de:"Nein", a_tr:"Hayır"}, {q:"Rannte die wilde Straßenmaus in Panik weg?", a_de:"Ja", a_tr:"Evet"}, {q:"Begann auch die Labormaus in Panik wegzurennen?", a_de:"Ja", a_tr:"Evet"}, {q:"Lernte die Labormaus die Angst von der anderen Maus?", a_de:"Ja", a_tr:"Evet"}, {q:"Sind soziale Ängste bei Mäusen ansteckend?", a_de:"Ja", a_tr:"Evet"} ]
}];lessonData["11_Eichhoernchen.mp3"] = [{
    text: "11. Pflegekind-Eichhörnchen. Im Tierreich leben manche Tiere gerne in großen Gruppen, andere bevorzugen es, komplett allein zu sein. Kanadische Eichhörnchen sind einzelgängerische Tiere. Das bedeutet, sie leben meist allein in ihren eigenen Bäumen. Normalerweise sind alleinlebende Tiere sehr egoistisch. Sie lassen nie fremde Tiere in ihre Familie oder ihr Territorium. Doch weibliche kanadische Eichhörnchen sind unglaublich anders und besonders. Manchmal verlieren Baby-Eichhörnchen ihre Eltern im gefährlichen Wald. Wenn ein weibliches Eichhörnchen diese armen, einsamen Waisen findet, adoptiert sie sie mutig. Sie kümmert sich um sie wie um ihre eigenen Babys. Die Männchen sind meist sehr wütend darüber, Futter zu teilen, aber die liebevollen Weibchen überreden ihre Partner, die neuen Babys zu akzeptieren. Diese unglaubliche Güte wird nie vergessen. Wenn die Waisen aufwachsen, erinnern sie sich an die Mutter, die ihr Leben gerettet hat. Um ihre tiefe Dankbarkeit zu zeigen, sammeln die jungen Eichhörnchen viele extra Nüsse. Sie bringen dieses Extra-Futter zurück zu ihrer Pflegemutter – als schöne Art, Danke zu sagen für ihre Liebe und ihren Schutz.",
    dict: { "tierreich":"hayvanlar alemi", "bevorzugen":"tercih ederler", "komplett":"tamamen", "einzelgängerische":"yalnız yaşayan", "bedeutet":"anlamına gelir", "fremde":"yabancı", "territorium":"bölge", "weibliche":"dişi", "verlieren":"kaybederler", "waisen":"yetimler", "adoptiert":"evlat edinir", "kümmert":"ilgilenir", "männchen":"erkekler", "liebevollen":"sevgi dolu", "überreden":"ikna ederler", "partner":"eş", "güte":"iyilik", "aufwachsen":"büyürler", "erinnern":"hatırlarlar", "gerettet":"kurtardı", "dankbarkeit":"minnettarlık", "nüsse":"fındık/ceviz", "pflegemutter":"koruyucu anne" },
    questions: [ {q:"Leben kanadische Eichhörnchen meist in großen Gruppen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Adoptieren weibliche Eichhörnchen einsame Waisen?", a_de:"Ja", a_tr:"Evet"}, {q:"Sind die Männchen meistens wütend darüber?", a_de:"Ja", a_tr:"Evet"}, {q:"Erinnern sich die Waisen an die Mutter, die sie gerettet hat?", a_de:"Ja", a_tr:"Evet"}, {q:"Sammeln sie extra Nüsse für ihre Pflegemutter?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["12_Hornissen.mp3"] = [{
    text: "12. Gebratene Hornissen. Japanische Riesen-Hornissen sind furchtbare, gefährliche Insekten. Sie greifen gerne Honigbienen an und fressen die weichen Babybienen. Der Stich einer Hornisse ist unglaublich giftig. Eine einzige Hornisse kann in wenigen Minuten Hunderte Bienen leicht töten. Sie greifen den Stock an, töten die Erwachsenen und fressen die Babys. Die meisten Honigbienen sind gegen diese massiven Killer völlig wehrlos. Doch eine spezielle Art japanischer Honigbienen hat eine brillante militärische Verteidigung entdeckt. Hornissen können Temperaturen über 46 Grad Celsius absolut nicht überleben. Diese speziellen Bienen jedoch überleben bis zu 48 Grad. Wenn die gefährlichen Hornissen in ihren Stock eindringen, fliehen die Bienen nicht. Stattdessen umzingeln Hunderte Bienen die Hornissen schnell. Sie bilden einen engen Ball um die Feinde. Dann beginnen alle Bienen gleichzeitig heftig mit den Flügeln zu zittern. Diese intensive Bewegung erhöht die Temperatur im Ball rasch. Die Hitze wird eingeschlossen. Bevor die eindringenden Hornissen überhaupt merken, was passiert, werden sie bei der extremen Hitze lebendig gekocht. Die klugen Bienen nutzen Teamarbeit und Körperwärme, um ihre riesigen Feinde komplett zu vernichten.",
    dict: { "hornissen":"eşek arıları", "furchtbare":"korkunç", "insekten":"böcekler", "weichen":"yumuşak", "stich":"sokma", "giftig":"zehirli", "töten":"öldürmek", "wehrlos":"savunmasız", "militärische":"askeri", "verteidigung":"savunma", "temperaturen":"sıcaklıklar", "überleben":"hayatta kalmak", "eindringen":"girmek/sızmak", "fliehen":"kaçarlar", "umzingeln":"etrafını sararlar", "feinde":"düşmanlar", "flügeln":"kanatlar", "zittern":"titremek", "intensive":"yoğun", "bewegung":"hareket", "erhöht":"artırır", "hitze":"ısı", "eingeschlossen":"hapsedilir", "gekocht":"pişirilir", "vernichten":"yok etmek" },
    questions: [ {q:"Sind Riesen-Hornissen gefährlich für Honigbienen?", a_de:"Ja", a_tr:"Evet"}, {q:"Fliehen die japanischen Honigbienen vor den Hornissen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Umzingeln Hunderte Bienen die Feinde?", a_de:"Ja", a_tr:"Evet"}, {q:"Erhöhen die Bienen durch Zittern die Temperatur?", a_de:"Ja", a_tr:"Evet"}, {q:"Werden die Hornissen bei extremer Hitze lebendig gekocht?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["13_Gibbons.mp3"] = [{
    text: "13. Gierige Gibbons. Gibbons sind sehr schnelle, agile Affen, die hoch in den Bäumen leben. Es ist normalerweise extrem schwierig für Jäger, sie zu fangen. Doch clevere Menschen in Indonesien haben einen sehr einfachen Weg gefunden, sie mit der eigenen Gier der Affen zu fangen. Jäger verkaufen diese Gibbons an ausländische Zoos, um gutes Geld zu machen. Um sie zu fangen, schneiden die Jäger ein kleines Loch in eine harte Kokosnuss. Sie stecken eine süße, leckere Banane hinein und binden die Kokosnuss fest an einen Baum. Gibbons haben einen ausgezeichneten Geruchssinn. Sie kommen schnell herunter, um die leckere Frucht zu holen. Ein Gibbon schiebt seine kleine, offene Hand durch das Loch, um die Banane zu greifen. Doch sobald er die Frucht hält, bildet sich seine Hand zu einer großen Faust. Die geschlossene Faust ist komplett gefangen. Sie ist zu groß, um durch das kleine Loch zurückgezogen zu werden. Um leicht zu entkommen, müsste der Gibbon nur die Banane loslassen. Doch der Affe ist unglaublich gierig. Er weigert sich absolut, das Futter fallen zu lassen. Wegen dieser dummen Gier gehen die Jäger einfach hin und fangen den gefangenen Affen leicht.",
    dict: { "agile":"çevik", "bäumen":"ağaçlar", "schwierig":"zor", "jäger":"avcılar", "einfachen":"basit", "weg":"yol/yöntem", "gier":"açgözlülük", "verkaufen":"satarlar", "ausländische":"yabancı", "schneiden":"keserler", "loch":"delik", "harte":"sert", "kokosnuss":"hindistan cevizi", "binden":"bağlarlar", "geruchssinn":"koku alma duyusu", "schiebt":"iter", "faust":"yumruk", "geschlossen":"kapalı", "gefangen":"tutsak/sıkışmış", "zurückgezogen":"geri çekilmiş", "entkommen":"kaçmak", "loslassen":"bırakmak", "weigert":"reddeder", "dummen":"aptalca" },
    questions: [ {q:"Sind Gibbons sehr langsame Affen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Schneiden Jäger ein Loch in eine Kokosnuss?", a_de:"Ja", a_tr:"Evet"}, {q:"Schiebt der Gibbon seine Hand durch das Loch?", a_de:"Ja", a_tr:"Evet"}, {q:"Bildet sich die Hand zu einer Faust, wenn er die Banane hält?", a_de:"Ja", a_tr:"Evet"}, {q:"Lässt der Gibbon die Banane los, um zu entkommen?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["14_Trauer.mp3"] = [{
    text: "14. Trauernde Tiere. Viele glauben, nur Menschen verstehen das traurige Konzept des Todes. Doch Wissenschaftler haben beobachtet, dass zwei spezielle Tierarten tatsächlich emotionale Beerdigungen für ihre toten Freunde abhalten. Eine ist der riesige Elefant, die andere ist ein kluger Vogel namens Häher. Wenn ein alter Elefant endlich stirbt, weigern sich die anderen Elefanten in der Familie, den Körper zu verlassen. Sie bedecken ihren toten Freund sorgfältig mit weichen Blättern, Erde und Zweigen. Sie stehen tagelang still um den Körper und machen tiefe, weinende Geräusche, um ihre Traurigkeit auszudrücken. Häher haben ein sehr ähnliches Ritual. Wenn ein Häher stirbt, macht der erste Vogel, der ihn findet, einen lauten Alarmruf. Das ruft alle nahen Vögel zusammen. Sie fliegen herunter und umzingeln den toten Vogel komplett. Sie sammeln kleine, trockene Stöcke und grüne Blätter, um den Körper ihres Freundes sanft zu bedecken. Sie hören für 24 Stunden komplett auf zu fliegen und zu jagen. Sie bleiben zusammen, um ihren Verlust zu betrauern. Diese schönen, traurigen Zeremonien sind unglaublich ähnlich zu menschlichen Beerdigungen und zeigen tiefe emotionale Bindungen.",
    dict: { "trauernde":"yas tutan", "konzept":"kavram", "beobachtet":"gözlemledi", "beerdigungen":"cenazeler", "abhalten":"düzenlerler", "elefant":"fil", "häher":"alakarga", "stirbt":"ölür", "weigern":"reddederler", "verlassen":"terk etmek", "bedecken":"örterler", "weichen":"yumuşak", "blättern":"yapraklar", "zweigen":"dallar", "weinende":"ağlayan", "geräusche":"sesler", "auszudrücken":"ifade etmek", "ritual":"ritüel", "alarmruf":"alarm çağrısı", "nahen":"yakın", "stöcke":"çubuklar", "sanft":"nazikçe", "jagen":"avlanmak", "verlust":"kayıp", "betrauern":"yas tutmak", "zeremonien":"törenler", "bindungen":"bağlar" },
    questions: [ {q:"Verstehen nur Menschen das Konzept des Todes?", a_de:"Nein", a_tr:"Hayır"}, {q:"Bedecken Elefanten ihren toten Freund mit Blättern und Zweigen?", a_de:"Ja", a_tr:"Evet"}, {q:"Machen sie weinende Geräusche?", a_de:"Ja", a_tr:"Evet"}, {q:"Sammeln Häher kleine Stöcke, um den Körper zu bedecken?", a_de:"Ja", a_tr:"Evet"}, {q:"Hören sie für 24 Stunden auf zu jagen?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["15_Hummer.mp3"] = [{
    text: "15. Nachbar-Hummer. Hummer sind normalerweise sehr aggressive, einzelgängerische Tiere, die allein am Meeresboden leben. Sie sind absolut nicht freundlich zueinander. Starke männliche Hummer kämpfen oft gewalttätig, um ihr persönliches Gebiet zu schützen. Manchmal kämpfen sie sogar bis zum Tod, um ihre Grenzen zu verteidigen. Doch ihr Verhalten ändert sich komplett, wenn eine fremde Gefahr auftaucht. Wenn ein großer Räuber kommt, um einen der Hummer anzugreifen, eilt der wütende Nachbar-Hummer sofort herbei, um zu helfen. Sie vergessen ihre alten Kämpfe komplett. Sie stehen Seite an Seite und jagen den großen Angreifer mit ihren scharfen Scheren weg. Nachdem sie den gemeinsamen Feind erfolgreich besiegt haben, werden die zwei Hummer respektvolle Freunde. Sie kämpfen nie wieder um Territorium für den Rest ihres Lebens. Sie leben friedlich als Nachbarn. Schließlich, wenn einer der Hummer vor Alter stirbt, übernimmt der überlebende Freund automatisch das leere Land des toten Hummers. Die anderen Hummer in der Gegend akzeptieren diesen friedlichen Machtwechsel respektvoll, ohne neue Kämpfe.",
    dict: { "hummer":"ıstakoz", "aggressive":"agresif", "meeresboden":"deniz tabanı", "freundlich":"dostça", "männliche":"erkek", "kämpfen":"savaşırlar/kavga ederler", "gebiet":"bölge", "schützen":"korumak", "grenzen":"sınırlar", "verteidigen":"savunmak", "fremde":"yabancı", "auftaucht":"ortaya çıkar", "räuber":"yırtıcı", "eilt":"acele eder", "herbei":"oraya/yardıma", "vergessen":"unuturlar", "scharfen":"keskin", "scheren":"kıskaçlar", "weg":"uzağa", "besiegt":"yendiler", "respektvolle":"saygılı", "nachbarn":"komşular", "übernimmt":"devralır", "überlebende":"hayatta kalan", "machtwechsel":"güç değişimi" },
    questions: [ {q:"Leben Hummer meist in großen Gruppen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Kämpfen starke männliche Hummer oft miteinander?", a_de:"Ja", a_tr:"Evet"}, {q:"Helfen sie einander, wenn ein großer Räuber kommt?", a_de:"Ja", a_tr:"Evet"}, {q:"Kämpfen die zwei Hummer danach weiter um das Territorium?", a_de:"Nein", a_tr:"Hayır"}, {q:"Übernimmt der überlebende Freund das leere Land, wenn der andere stirbt?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["16_Hyaenen.mp3"] = [{
    text: "16. Vetternwirtschaft bei Hyänen. Hyänen sind berühmte afrikanische Aasfresser, die oft die Reste von größeren Räubern fressen. Ihre Gesellschaft ist sehr anders als bei vielen anderen Tiergruppen. In einem Hyänenrudel sind die Weibchen immer die absoluten Anführerinnen. Die mächtigste, aggressive Alpha-Weibchen kontrolliert die gesamte Gruppe komplett, und alle müssen ihre Regeln streng befolgen. Die Männchen akzeptieren friedlich ihren niedrigeren Rang. Doch das Rudel ist kein fairer Ort. Die Alpha-Weibchen praktiziert starke Vetternwirtschaft – sie bevorzugt immer ihre eigene Familie. Sie gibt ihren eigenen Kindern immer das beste Futter und Privilegien, auch wenn andere Hyänen viel stärker oder klüger sind. Ihre Babys bekommen totalen Schutz einfach wegen ihres königlichen Blutes. Trotz dieser unfairen Bevorzugung macht die strenge soziale Ordnung die Gruppe extrem gefährlich. Indem sie perfekt unter dem Kommando der weiblichen Anführerin zusammenarbeiten, kann ein großes Rudel Hyänen leicht Futter von riesigen Löwen stehlen. Wenn ein Löwe Widerstand leistet, greifen die organisierten Hyänen ihn gewalttätig an und töten ihn.",
    dict: { "vetternwirtschaft":"adam kayırma", "aasfresser":"leş yiyiciler", "reste":"kalıntılar", "räubern":"yırtıcılar", "gesellschaft":"toplum", "hyänenrudel":"sırtlan sürüsü", "weibchen":"dişiler", "anführerinnen":"kadın liderler", "mächtigste":"en güçlü", "streng":"sıkı/katı", "befolgen":"uymak", "niedrigeren":"daha düşük", "rang":"rütbe", "praktiziert":"uygular", "bevorzugt":"tercih eder/kayırır", "privilegien":"ayrıcalıklar", "blutes":"kanın", "unfairen":"adaletsiz", "ordnung":"düzen", "kommando":"komuta", "löwen":"aslanlar", "widerstand":"direniş", "leistet":"gösterir" },
    questions: [ {q:"Sind bei den Hyänen die Männchen die Anführer?", a_de:"Nein", a_tr:"Hayır"}, {q:"Bevorzugt die Alpha-Weibchen ihre eigene Familie?", a_de:"Ja", a_tr:"Evet"}, {q:"Bekommen ihre Babys totalen Schutz?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist das Rudel durch die strenge soziale Ordnung sehr gefährlich?", a_de:"Ja", a_tr:"Evet"}, {q:"Können organisierte Hyänen einen Löwen töten?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["17_Sklavenameisen.mp3"] = [{
    text: "17. Sklavenhändler-Ameisen. Tief im Amazonas-Dschungel gibt es eine sehr grausame und aggressive Ameisenart. Diese gefährlichen Ameisen haben lange, scharfe Zähne außerhalb ihres Mundes. Sie nutzen diese Zähne wie tödliche Schwerter, um Feinde im Kampf leicht zu töten. Doch diese langen Zähne schaffen ein massives Problem: Die Ameisen können ihr eigenes Futter physisch nicht kauen. Um das zu lösen, entwickelten sie eine furchtbare, imperialistische Strategie. Die Kriegerameisen marschieren aus und greifen die friedlichen Nester kleinerer, schwächerer Ameisen an. Sie töten rücksichtslos alle erwachsenen Verteidiger. Dann stehlen sie die ungeschlüpften Eier der kleinen Ameisen und tragen sie zurück in ihr eigenes Nest. Wenn diese gestohlenen Eier schlüpfen, wissen die jungen Ameisen nicht, dass sie entführt wurden. Ihr natürlicher Instinkt sagt ihnen, hart zu arbeiten. Sie gehen raus, sammeln frisches Futter und bringen es zurück. Wichtigster Punkt: Sie kauen das Futter und füttern es direkt in die Mäuler ihrer grausamen Herren. Wenn die Killerameisen wieder stark sind, richten sie alle ihre loyalen Sklaven brutal hin und marschieren aus, um ein brandneues Nest anzugreifen.",
    dict: { "sklavenhändler":"köle tüccarı", "grausame":"zalim", "zähne":"dişler", "außerhalb":"dışında", "mundes":"ağız", "schwerter":"kılıçlar", "physisch":"fiziksel olarak", "kauen":"çiğnemek", "lösen":"çözmek", "imperialistische":"emperyalist", "strategie":"strateji", "marschieren":"yürürler", "friedlichen":"huzurlu", "nester":"yuvalar", "schwächerer":"daha zayıf", "rücksichtslos":"acımasızca", "verteidiger":"savunucular", "stehlen":"çalarlar", "ungeschlüpften":"çıkmamış", "eier":"yumurtalar", "schlüpfen":"yumurtadan çıkmak", "instinkt":"içgüdü", "sammeln":"toplarlar", "füttern":"beslerler", "loyalen":"sadık", "sklaven":"köleler", "brutal":"acımasızca", "richten":"infaz ederler/richten hin" },
    questions: [ {q:"Haben diese gefährlichen Ameisen lange, scharfe Zähne?", a_de:"Ja", a_tr:"Evet"}, {q:"Können sie ihr eigenes Futter kauen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Stehlen sie die Eier von kleineren Ameisen?", a_de:"Ja", a_tr:"Evet"}, {q:"Kauen die Sklaven-Ameisen das Futter für ihre Herren?", a_de:"Ja", a_tr:"Evet"}, {q:"Töten die Killerameisen ihre Sklaven am Ende?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["18_Gorillas.mp3"] = [{
    text: "18. Handelnde Gorillas. Wissenschaftler führten ein faszinierendes Wirtschaftsexperiment mit vier intelligenten Gorillas durch. Die Gorillas lebten in vier separaten Käfigen in einem großen Raum. Jeden Morgen gab ein Forscher jedem Gorilla einige Plastik-Token. Nachmittags bot ein anderer Forscher ihnen einfache Gurken an und nahm die Token im Tausch. Die Gorillas akzeptierten diesen einfachen Handel fröhlich. Eines Tages änderte der Forscher die Regeln. Er gab dem ersten Gorilla leckere, süße Trauben für seine Token, aber den anderen drei nur die langweiligen Gurken. Am nächsten Tag streikten die drei wütenden Gorillas. Sie weigerten sich komplett, ihre Token für langweilige Gurken abzugeben. Sie forderten auch die süßen Trauben. Schließlich gab der Forscher dem ersten Gorilla eine tolle, leckere Banane und den anderen drei die Trauben. Die drei Gorillas waren wieder wütend! Diesmal weigerten sie sich, ihre Token für Trauben zu geben. Sie forderten wütend eine Banane für ihr „Geld“. Sie verstanden perfekt das Konzept unfairer Löhne und lernten, aggressiv mit ihrer Währung für das absolut beste mögliche Futter zu handeln.",
    dict: { "handelnde":"ticaret yapan", "wirtschaftsexperiment":"ekonomi deneyi", "separaten":"ayrı", "forscher":"araştırmacı", "token":"jeton", "nachmittags":"öğleden sonraları", "bot":"sundu", "gurken":"salatalıklar", "tausch":"takas", "änderte":"değiştirdi", "trauben":"üzümler", "langweiligen":"sıkıcı", "streikten":"grev yaptılar", "weigerten":"reddettiler", "abzugeben":"teslim etmek", "forderten":"talep ettiler", "banane":"muz", "diesmal":"bu kez", "löhne":"maaşlar/ücretler", "währung":"para birimi", "handeln":"ticaret yapmak" },
    questions: [ {q:"Lebten die vier Gorillas in separaten Käfigen?", a_de:"Ja", a_tr:"Evet"}, {q:"Bekamen die Gorillas Plastik-Token von den Forschern?", a_de:"Ja", a_tr:"Evet"}, {q:"Akzeptierten alle Gorillas langweilige Gurken, als ein Gorilla Trauben bekam?", a_de:"Nein", a_tr:"Hayır"}, {q:"Streikten die Gorillas?", a_de:"Ja", a_tr:"Evet"}, {q:"Verstanden die Gorillas das Konzept von unfairen Löhnen?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["19_Pinguine.mp3"] = [{
    text: "19. Trickreiche Pinguine. Die meisten Pinguine leben in komplett gefrorenen, eisigen Umgebungen. Da es keine Bäume oder Gras gibt, sind kleine, glatte Steine extrem wertvoll für sie. Sie brauchen diese kleinen Steine unbedingt, um sichere, trockene Nester auf dem Eis zu bauen. Wenn ein weiblicher Pinguin kein gutes Stein-Nest hat, kann er seine kostbaren Eier nicht legen. Steine sammeln ist also eine Frage von Leben und Tod. Pinguine sind generell monogame Tiere – sie bleiben einem einzigen Partner treu. Doch einige sehr clevere und trickreiche weibliche Pinguine haben eine skandalöse Methode entdeckt, um extra Steine zu bekommen. Während ihre treuen Ehemänner weg sind, um Fisch zu jagen, nähern sich diese Weibchen jungen, single Männchen. Sie flirten mit den Männchen und tun so, als wollten sie sich paaren. Die aufgeregten jungen Männchen bringen den Weibchen schnell schöne Steine als romantische Geschenke. Doch sobald die trickreichen Weibchen die wertvollen Steine haben, rennen sie sofort weg. Sie verweigern komplett jeden romantischen Kontakt und lassen die jungen Männchen total betrogen und verwirrt zurück.",
    dict: { "trickreiche":"hilekar", "gefrorenen":"donmuş", "eisigen":"buzlu", "umgebungen":"çevreler", "glatte":"pürüzsüz", "steine":"taşlar", "wertvoll":"değerli", "unbedingt":"kesinlikle", "trockene":"kuru", "weiblicher":"dişi", "kostbaren":"değerli", "monogame":"tek eşli", "treu":"sadık", "skandalöse":"skandal", "methode":"yöntem", "ehemänner":"kocalar", "nähern":"yaklaşırlar", "single":"bekar", "flirten":"flört ederler", "paaren":"çiftleşmek", "geschenke":"hediyeler", "rennen":"koşarlar", "verweigern":"reddederler", "kontakt":"temas", "betrogen":"aldatılmış", "verwirrt":"kafası karışmış" },
    questions: [ {q:"Sind kleine Steine extrem wertvoll für Pinguine?", a_de:"Ja", a_tr:"Evet"}, {q:"Sind Pinguine generell monogame Tiere?", a_de:"Ja", a_tr:"Evet"}, {q:"Flirten trickreiche Weibchen mit jungen, single Männchen?", a_de:"Ja", a_tr:"Evet"}, {q:"Bringen die jungen Männchen schöne Steine als Geschenke?", a_de:"Ja", a_tr:"Evet"}, {q:"Paaren sich die trickreichen Weibchen mit den jungen Männchen?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["20_Waschbaeren.mp3"] = [{
    text: "20. Urbanisierte Waschbären. In einer modernen Stadt zu leben erfordert viel bessere Problemlösungsfähigkeiten als in einem ruhigen Wald. Diese Regel passt perfekt auf Waschbären. Viele clevere Waschbären sind in menschliche Städte gezogen, weil sie einen unglaublich einfachen Weg zum Essen gefunden haben. Statt wilder Tiere zu jagen, stehlen sie einfach leckere Essensreste aus menschlichen Mülltonnen. Im Laufe der Zeit haben diese Stadt-Waschbären genau gelernt, wie man komplexe, schwere Deckel öffnet, um an den Müll zu kommen. Wissenschaftler wollten ihre Intelligenz testen. Sie fingen einige hungrige wilde Waschbären aus dem tiefen Wald und brachten sie in die Stadt. Die wilden Waschbären rochen schnell das Futter in den städtischen Mülltonnen. Doch ihnen fehlten die nötigen urbanen Fähigkeiten. Egal wie sehr sie zogen und kratzten, sie konnten die komplizierten Deckel einfach nicht öffnen. Schließlich gaben die frustrierten Wald-Waschbären komplett auf und rannten zurück in den Wald, um Käfer zu jagen. Dieses Experiment bewies, dass die schwierige urbane Umgebung Stadt-Waschbären zwingt, sich zu entwickeln und hochentwickelte Überlebensfähigkeiten zu entwickeln.",
    dict: { "urbanisierte":"şehirleşmiş", "waschbären":"rakunlar", "erfordert":"gerektirir", "problemlösungsfähigkeiten":"problem çözme yetenekleri", "passt":"uyar", "gezogen":"taşınmış", "essensreste":"yemek artıkları", "mülltonnen":"çöp kutuları", "laufe":"zamanla/sürecinde", "komplexe":"karmaşık", "deckel":"kapaklar", "fingen":"yakaladılar", "städtischen":"kentsel", "fehlten":"eksikti", "nötigen":"gerekli", "fähigkeiten":"yetenekler", "egal":"ne kadar... olursa olsun", "zogen":"çektiler", "kratzten":"tırmaladılar", "komplizierten":"karmaşık", "frustrierten":"hüsrana uğramış", "bewies":"kanıtladı", "hochentwickelte":"gelişmiş" },
    questions: [ {q:"Haben Stadt-Waschbären gelernt, wie man komplexe Deckel öffnet?", a_de:"Ja", a_tr:"Evet"}, {q:"Fingen Wissenschaftler wilde Waschbären aus dem Wald?", a_de:"Ja", a_tr:"Evet"}, {q:"Konnten die wilden Waschbären die Mülltonnen in der Stadt öffnen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Gaben die wilden Waschbären auf und rannten zurück in den Wald?", a_de:"Ja", a_tr:"Evet"}, {q:"Zwingt die urbane Umgebung Waschbären, sich zu entwickeln?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["21_Geier.mp3"] = [{
    text: "21. Geier und Teamarbeit. Die meisten Menschen denken, Geier seien hässliche, ekelige Vögel, doch sie sind eigentlich unglaublich wichtig für unsere natürliche Umwelt. Sie wirken als Natursanitäter. Sie fressen schnell tote Tiere, damit das verrottende Fleisch keine schrecklichen Krankheiten verbreitet. In Gebieten, wo Geier verschwinden, wachsen tödliche Bakterien und machen die lokalen Menschenpopulationen sehr krank. Geier sind Meister der spezialisierten Teamarbeit. Eine große Schar kann eine massive tote Giraffe in weniger als drei Stunden komplett fressen. Sie teilen die Arbeit perfekt ein. Die älteren, erfahrenen Geier fressen die weichen inneren Organe, während die jüngeren Vögel die harten Knochen säubern. Während die Hauptgruppe sicher frisst, stehen die größten und stärksten Geier im Kreis um das Futter. Sie agieren als strenge Sicherheitswachen, um wütende Hyänen und Schakale fernzuhalten. Wenn die Hauptgruppe endlich satt ist, treten die loyalen Wachen vor, um ihren fairen Anteil am Fleisch zu fressen. Wenn sie fertig sind, ist das gefährliche tote Tier komplett aus der Umwelt gelöscht.",
    dict: { "geier":"akbabalar", "teamarbeit":"takım çalışması", "hässliche":"çirkin", "ekelige":"iğrenç", "umwelt":"çevre", "natursanitäter":"doğa temizleyicileri", "verrottende":"çürüyen", "verbreitet":"yayar", "bakterien":"bakteriler", "menschenpopulationen":"insan popülasyonları", "schar":"sürü", "giraffe":"zürafa", "teilen":"bölerler/paylaşırlar", "erfahrenen":"deneyimli", "inneren":"iç", "organe":"organlar", "jüngeren":"genç", "säubern":"temizlerler", "hauptgruppe":"ana grup", "sicherheitswachen":"güvenlik görevlileri", "fernzuhalten":"uzak tutmak", "satt":"tok", "treten":"adım atarlar", "anteil":"pay", "gelöscht":"silindi/yok edildi" },
    questions: [ {q:"Sind Geier unglaublich wichtig für die Umwelt?", a_de:"Ja", a_tr:"Evet"}, {q:"Fressen sie tote Tiere, damit sich keine Bakterien verbreiten?", a_de:"Ja", a_tr:"Evet"}, {q:"Fressen die erfahrenen Geier die weichen inneren Organe?", a_de:"Ja", a_tr:"Evet"}, {q:"Stehen die stärksten Geier im Kreis, um Schakale fernzuhalten?", a_de:"Ja", a_tr:"Evet"}, {q:"Fressen die Wachen am Ende ihren fairen Anteil?", a_de:"Ja", a_tr:"Evet"} ]
}];
